### ISSUE TITLE
convert_katakana_to_hiragana_string crashes on チームワーク (Teamwork)

### ISSUE THREAD

**Issue by fhars** [mrahhal/rust-japanese#1]
It seems like it is missing logic for ワー and ヲー.

**Comment by mrahhal** [comment]
ワー is missing yes, but not sure what to do with ヲー. Any real world examples of this, or any suggestions what it should be in hiragana? Could be をお I guess.
Would have to do something about it anyway so that it doesn't crash though.

**Comment by mrahhal** [comment]
- `"チームワーク"` -> `"ちいむわあく"`
- `"ヲー"` -> `"をお"`

Looks good? Gonna also change it so instead of crashing on unknown rules it'll just output the same character.

**Comment by fhars** [comment]
You can find some uses ヲー on the web. I even found a current usage of ヰー (wii): https://gyoza.info/%E3%81%95%E3%82%88%E3%81%AA%E3%82%89%E3%82%B9%E3%83%B0%E3%83%BC%E3%83%88%E3%83%9D%E3%83%BC%E3%83%85%EF%BC%81%E7%A5%9E%E4%BF%9D%E7%94%BA%E3%81%AE%E9%A4%83%E5%AD%90%E3%81%AE%E5%90%8D%E5%BA%97%E3%81%8C
